### ISSUE TITLE
Gallium 9 setup step needs clarification

### ISSUE THREAD

**Issue by douglasg14b** [tatsujb/installFAFscript#10]
When running the `eval "$(cat .bashrc | tail -n +10)"` command there needs to be a note that it is expected that you are in your home directory. Took me a bit to figure that out...

Side note, can an explanation of what this command is doing be added?

**Comment by tatsujb** [comment]
sure, although there may be no need for it down the line. I'm in the process of working those out of the script.

note that eval is EVIL. `eval "$(cat .bashrc | tail -n +10)"` is a hack that performs `source .bashrc` FOR the current open terminal despite the escape in .bashrc that exists **specifically** to prevent this. as it could be a security risk.

Imagine (I'm making this up, I'm no security expert) I add "let user x do what he wants" to .bashrc then source said bashrc to the same terminal **still** running the script that added it. it can then be followed up with actions from said user right on the following lines and still with whatever rights were already optained wheras child terminal processes would indeed have had those bashrc changes loaded but without the right since they aren't inheried.

I used it originally because i had everything in the same thread and FAF was failing with basically "no INSTALL4J variable" even though I had added it to bashrc. 

to avoid another manual step of starting FAF yourself I added this. I'm pretty sure with the current setup where it's started by a new terminal I can remove it and have FAF still start.
