### ISSUE TITLE
Installer doesnt work on clean ubuntu 19.04

### ISSUE THREAD

**Issue by robert2411** [tatsujb/installFAFscript#11]
To add to the manual?
I needed to install pv and xterm on ubuntu 19.04 to get your script to work

**Comment by tatsujb** [comment]
yeah. I've been caught up in stuff so haven't been able to contribute to this recently. Maybe down the line I'll make another commit making things robust. right now I'm strapped for time.

the script right now is failling on the if case line 373 and you end up in line 383. same at 699 to 709.

I should generally have ubuntu and lockalikes in my "else" for robustness, since ubuntu is the base of my script.

**Comment by tatsujb** [comment]
would you please try again :) ? I commited an untested fix which should resolve this. 

the big one whcih remove eval should come. maybe this weekend or the one after.
